# Generated by Django 2.2.1 on 2019-05-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_order_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
